version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: gopher_postgres
    environment:
      POSTGRES_USER: gopher
      POSTGRES_PASSWORD: gopher
      POSTGRES_DB: gopher_dev
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: gopher_redis
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redisdata:/data
